"""SatQuery AI — agentic vision-language analysis of remote-sensing imagery.

Reference implementation for SIH26167 (ISRO). The build contract is
`../docs/03_Model_Specification.md`; the structure is `../docs/05_System_Design.md`;
the reasoning behind each structural choice is in `../docs/ADR/`.

The rule the whole package is arranged around:

    Vision models produce the facts. The language layer only phrases them.
    Never the reverse.

`pipeline.answer()` receives an `EvidenceSet` and never a raster, so a number
in an answer is always traceable to something that was measured and passed a
confidence gate. That is ADR-007, enforced by the type signature rather than
by discipline.

What is real and what is simulated
----------------------------------
**Simulated:** the pixel values. Cartosat-2S and RISAT imagery cannot be
obtained and the ISRO/SAC evaluation set is explicitly undisclosed, so scenes
are generated by `scene.py`.

**Real:** everything that reads them. The scenes are genuine GeoTIFFs with a
correct affine geotransform in EPSG:4326. The Lee speckle filter, Otsu
thresholding, connected-component labelling, change vector analysis, NDVI and
NDWI, phase-correlation co-registration, the pixel-to-Earth transform, the
router's classification and validation, the confidence gate and the evidence
schema are all real implementations operating on those rasters. None of them
knows the imagery is synthetic.

Ground truth is recorded in `Scene.truth` and read **only** by `evaluate.py`.
No analysis module has access to it — which is the only arrangement under which
a synthetic benchmark measures anything.
"""

__version__ = "0.4.0"

__all__ = [
    "cv", "datasets", "errors", "evaluate", "evidence", "pipeline",
    "raster", "report", "router", "runtime", "scene", "specialists",
    "store", "validate",
]
